//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbMecenat.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalIntervention
    {
        public int Id { get; set; }
        public string NomTable { get; set; }
        public string OperationEffectuee { get; set; }
        public System.DateTime DateHeure { get; set; }
        public string ReferenceEnregistrement { get; set; }
        public int IdUtilisateur { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
