//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbMecenat.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partenariat
    {
        public int id { get; set; }
        public System.DateTime DatePartenariat { get; set; }
        public Nullable<decimal> BudgetPrevisionnel { get; set; }
        public Nullable<decimal> BudgetReel { get; set; }
        public int IdAssociation { get; set; }
        public Nullable<int> idActionMecenat { get; set; }
    
        public virtual ActionMecenat ActionMecenat { get; set; }
        public virtual Association Association { get; set; }
    }
}
